#ifndef GUARD_CONSTANTS_GAME_CORNER_GACHA_H
#define GUARD_CONSTANTS_GAME_CORNER_GACHA_H

enum GachaMode
{
    GACHA_BASIC,
    GACHA_GREAT,
    GACHA_ULTRA,
    GACHA_MASTER,
    GACHA_COUNT,
};

#endif // GUARD_CONSTANTS_GAME_CORNER_GACHA_H
