#ifndef GUARD_CONSTANTS_ITEM_MENU_FRLG_H
#define GUARD_CONSTANTS_ITEM_MENU_FRLG_H

enum {
    ITEMMENUACTION_USE,
    ITEMMENUACTION_TOSS,
    ITEMMENUACTION_REGISTER,
    ITEMMENUACTION_GIVE,
    ITEMMENUACTION_CANCEL,
    ITEMMENUACTION_BATTLE_USE,
    ITEMMENUACTION_CHECK,
    ITEMMENUACTION_OPEN,
    ITEMMENUACTION_OPEN_BERRIES,
    ITEMMENUACTION_WALK,
    ITEMMENUACTION_DESELECT,
    ITEMMENUACTION_SORT_NAME,
    ITEMMENUACTION_SORT_AMOUNT,
    ITEMMENUACTION_SORT_TYPE,
    ITEMMENUACTION_SORT_INDEX,
    ITEMMENUACTION_CHECK_TAG,
    ITEMMENUACTION_CONFIRM,
    ITEMMENUACTION_SELECT_BUTTON,
    ITEMMENUACTION_L_BUTTON,
    ITEMMENUACTION_R_BUTTON,
    ITEMMENUACTION_DUMMY,
    ITEMMENUACTION_COUNT,
};

#endif //GUARD_CONSTANTS_ITEM_MENU_FRLG_H
