#ifndef GUARD_CONSTANTS_MUSIC_PLAYER_H
#define GUARD_CONSTANTS_MUSIC_PLAYER_H

enum MP3PlayerTracks
{
    MUSIC_TRACK_ZGS_VS_WILD,
    MUSIC_TRACK_ZGS_VS_TRAINER,
    MUSIC_TRACK_ZGS_VS_CHAMPION,
    MUSIC_TRACK_ZGS_VICTORY_WILD,
    MUSIC_TRACK_ZGS_VICTORY_TRAINER,
    MUSIC_TRACK_COUNT,
};

enum MP3Menus
{
    MP3_MENU_MAIN,
    MP3_MENU_PLAY_MUSIC,
    MP3_MENU_RADIO,
    MP3_MENU_COUNT,
};

enum MP3Background
{
    MP3_BG_1,
    MP3_BG_2,
    MP3_BG_3,
};

enum MP3WindowIds
{
    MP3_WINDOW_HEADER,
    MP3_WINDOW_DESCRIPTION,
    MP3_WINDOW_WEEKDAY,
    MP3_WINDOW_STATION,
    MP3_WINDOW_LIST,
};

#endif // GUARD_CONSTANTS_MUSIC_PLAYER_H
