#ifndef GUARD_CONSTANTS_POKEBALL_H
#define GUARD_CONSTANTS_POKEBALL_H

enum PokeBall
{
    BALL_STRANGE = 0,
    BALL_POKE = 1,
    BALL_GREAT = 2,
    BALL_ULTRA = 3,
    BALL_MASTER = 4,
    BALL_PREMIER = 5,
    BALL_HEAL = 6,
    BALL_NET = 7,
    BALL_NEST = 8,
    BALL_DIVE = 9,
    BALL_DUSK = 10,
    BALL_TIMER = 11,
    BALL_QUICK = 12,
    BALL_REPEAT = 13,
    BALL_LUXURY = 14,
    BALL_LEVEL = 15,
    BALL_LURE = 16,
    BALL_MOON = 17,
    BALL_FRIEND = 18,
    BALL_LOVE = 19,
    BALL_FAST = 20,
    BALL_HEAVY = 21,
    BALL_DREAM = 22,
    BALL_SAFARI = 23,
    BALL_FOUL = 24,
    BALL_IGNITE = 25,
    BALL_BOMB = 26,
    BALL_PARK = 27,
    BALL_BEAST = 28,
    BALL_CHERISH = 29,
    BALL_POKE2 = 30,
    BALL_GREAT2 = 31,
    BALL_ULTRA2 = 32,
    POKEBALL_COUNT
};

#endif // GUARD_CONSTANTS_POKEBALL_H
